"""EA club names (FC 25 / FC 27 ratings data) -> our team_id and display name (D54).

EA's data has no club ids and uses EA's in-game names, including unlicensed ones ("Lombardia FC" = Inter).
Built in stage 10 from the stage 09 majority vote: each EA club was matched to the club its players played for
in FC 24 (SoFIFA), or in FC 26 for clubs that are new to the top 5 after FC 25. Every entry was checked by eye.
The display name is the name we already show for that team_id (FIFA 15 - FC 24 JSON), or the FC 26 SoFIFA name
for clubs we have never shown. build.py fails on any top-5 club that is missing here.
"""

# EA club name -> (team_id, display name). Grouped by the league where the club first appears (FC 25, else FC 27);
# the league of a club in a given version always comes from that version's data.
EA_CLUBS: dict[str, tuple[int, str]] = {
    # Premier League
    "AFC Bournemouth": (1943, "AFC Bournemouth"),
    "Arsenal": (1, "Arsenal"),
    "Aston Villa": (2, "Aston Villa"),
    "Brentford": (1925, "Brentford"),
    "Brighton": (1808, "Brighton & Hove Albion"),
    "Chelsea": (5, "Chelsea"),
    "Coventry City": (1800, "Coventry City"),
    "Crystal Palace": (1799, "Crystal Palace"),
    "Everton": (7, "Everton"),
    "Fulham": (144, "Fulham"),
    "Hull City": (1952, "Hull City"),
    "Ipswich": (94, "Ipswich Town"),
    "Leeds United": (8, "Leeds United"),
    "Leicester City": (95, "Leicester City"),
    "Liverpool": (9, "Liverpool"),
    "Man Utd": (11, "Manchester United"),
    "Manchester City": (10, "Manchester City"),
    "Newcastle Utd": (13, "Newcastle United"),
    "Nott'm Forest": (14, "Nottingham Forest"),
    "Southampton": (17, "Southampton"),
    "Spurs": (18, "Tottenham Hotspur"),
    "Sunderland": (106, "Sunderland"),
    "West Ham": (19, "West Ham United"),
    "Wolves": (110, "Wolverhampton Wanderers"),
    # La Liga
    "Athletic Club": (448, "Athletic Club"),
    "Atlético de Madrid": (240, "Atlético Madrid"),
    "CA Osasuna": (479, "Osasuna"),
    "CD Leganés": (100888, "Leganés"),
    "Celta": (450, "Celta de Vigo"),
    "D. Alavés": (463, "Deportivo Alavés"),
    "Elche CF": (468, "Elche"),
    "FC Barcelona": (241, "FC Barcelona"),
    "Getafe CF": (1860, "Getafe"),
    "Girona FC": (110062, "Girona"),
    "Levante UD": (1853, "Levante"),
    "Málaga CF": (573, "Málaga"),
    "R. Racing Club": (456, "Racing Santander"),
    "R. Valladolid CF": (462, "Real Valladolid"),
    "Rayo Vallecano": (480, "Rayo Vallecano"),
    "RC Celta": (450, "Celta de Vigo"),
    "RC Deportivo": (242, "Deportivo de La Coruña"),
    "RCD Espanyol": (452, "Espanyol"),
    "RCD Mallorca": (453, "Mallorca"),
    "Real Betis": (449, "Real Betis"),
    "Real Madrid": (243, "Real Madrid"),
    "Real Sociedad": (457, "Real Sociedad"),
    "Sevilla FC": (481, "Sevilla"),
    "UD Las Palmas": (472, "Las Palmas"),
    "Valencia CF": (461, "Valencia"),
    "Villarreal CF": (483, "Villarreal"),
    # Serie A
    "AS Roma": (52, "Roma"),
    "Bergamo Calcio": (39, "Atalanta"),
    "Bologna": (189, "Bologna"),
    "Cagliari": (1842, "Cagliari"),
    "Como": (1745, "Como"),
    "Empoli": (1746, "Empoli"),
    "Fiorentina": (110374, "Fiorentina"),
    "Frosinone": (111657, "Frosinone"),
    "Genoa": (110556, "Genoa"),
    "Hellas Verona": (206, "Hellas Verona"),
    "Juventus": (45, "Juventus"),
    "Latium": (46, "Lazio"),
    "Lecce": (347, "Lecce"),
    "Lombardia FC": (44, "Inter"),
    "Milano FC": (47, "Milan"),
    "Monza": (111811, "Monza"),
    "Parma": (50, "Parma"),
    "Sassuolo": (111974, "Sassuolo"),
    "SSC Napoli": (48, "Napoli"),
    "Torino": (54, "Torino"),
    "Udinese": (55, "Udinese"),
    "Venezia": (205, "Venezia"),
    # Bundesliga
    "1. FC Köln": (31, "FC Köln"),
    "1. FSV Mainz 05": (169, "FSV Mainz 05"),
    "Borussia Dortmund": (22, "Borussia Dortmund"),
    "FC Augsburg": (100409, "FC Augsburg"),
    "FC Bayern München": (21, "FC Bayern München"),
    "FC Schalke 04": (34, "Schalke 04"),
    "FC St. Pauli": (110329, "FC St. Pauli"),
    "Frankfurt": (1824, "Eintracht Frankfurt"),
    "Hamburger SV": (28, "Hamburger SV"),
    "Heidenheim": (111235, "Heidenheim"),
    "Holstein Kiel": (576, "Holstein Kiel"),
    "Leverkusen": (32, "Bayer 04 Leverkusen"),
    "M'gladbach": (23, "Borussia Mönchengladbach"),
    "RB Leipzig": (112172, "RB Leipzig"),
    "SC Freiburg": (25, "SC Freiburg"),
    "SC Paderborn 07": (10030, "Paderborn"),
    "SV Elversberg": (580, "SV Elversberg"),
    "SV Werder Bremen": (38, "Werder Bremen"),
    "TSG Hoffenheim": (10029, "TSG Hoffenheim"),
    "Union Berlin": (1831, "FC Union Berlin"),
    "VfB Stuttgart": (36, "VfB Stuttgart"),
    "VfL Bochum 1848": (160, "VfL Bochum 1848"),
    "VfL Wolfsburg": (175, "VfL Wolfsburg"),
    # Ligue 1
    "AJ Auxerre": (57, "Auxerre"),
    "Angers SCO": (1530, "Angers SCO"),
    "AS Monaco": (69, "Monaco"),
    "AS Saint-Étienne": (1819, "Saint-Étienne"),
    "ESTAC Troyes": (294, "Troyes"),
    "FC Lorient": (217, "Lorient"),
    "FC Nantes": (71, "Nantes"),
    "Havre AC": (1738, "Le Havre"),
    "Le Mans FC": (1739, "Le Mans FC"),
    "LOSC Lille": (65, "Lille"),
    "Montpellier": (70, "Montpellier"),
    "OGC Nice": (72, "Nice"),
    "OL": (66, "Olympique Lyonnais"),
    "OM": (219, "Olympique de Marseille"),
    "Paris FC": (111817, "Paris FC"),
    "Paris SG": (73, "Paris Saint Germain"),
    "RC Lens": (64, "Lens"),
    "Stade Brestois 29": (378, "Brest"),
    "Stade de Reims": (379, "Stade de Reims"),
    "Stade Rennais FC": (74, "Rennes"),
    "Strasbourg": (76, "Strasbourg"),
    "Toulouse FC": (1809, "Toulouse"),
}
