"""Stage 01 data exploration.

Reads the raw Kaggle CSVs (male_players.csv, male_teams.csv) and writes
docs/reports/01-data-exploration.md with tables answering the stage 01 questions.

Run from the repository root:
    pipeline/.venv/Scripts/python pipeline/explore.py      (Windows)
    pipeline/.venv/bin/python pipeline/explore.py          (macOS / Linux)

Everything below the MANUAL_MARKER line in an existing report is preserved on re-run,
so hand-written findings are not lost.
"""

import gzip
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "data" / "raw" / "FIFA 15-24"
PLAYERS_CSV = RAW_DIR / "male_players.csv"
TEAMS_CSV = RAW_DIR / "male_teams.csv"
REPORT = ROOT / "docs" / "reports" / "01-data-exploration.md"
MANUAL_MARKER = "<!-- MANUAL SECTION BELOW: preserved when explore.py is re-run -->"

# Target leagues: detected by (name, country) in the latest version, then tracked by league_id
TARGET_LEAGUES = [
    ("EPL", "Premier League", "England"),
    ("LaLiga", "La Liga", "Spain"),
    ("SerieA", "Serie A", "Italy"),
    ("Bundesliga", "Bundesliga", "Germany"),
    ("Ligue1", "Ligue 1", "France"),
]

NON_XI = {"SUB", "RES"}

# Position groups used to derive a D-M-A formation
DEFENDERS = {"LWB", "LB", "LCB", "CB", "RCB", "RB", "RWB"}
MIDFIELDERS = {"LDM", "CDM", "RDM", "LM", "LCM", "CM", "RCM", "RM", "LAM", "CAM", "RAM"}
ATTACKERS = {"LW", "LF", "CF", "RF", "RW", "LS", "ST", "RS"}

# Display order for an XI: GK, defence, midfield, attack (left to right)
POSITION_ORDER = [
    "GK",
    "LWB", "LB", "LCB", "CB", "RCB", "RB", "RWB",
    "LDM", "CDM", "RDM", "LM", "LCM", "CM", "RCM", "RM", "LAM", "CAM", "RAM",
    "LW", "LF", "CF", "RF", "RW", "LS", "ST", "RS",
]
POS_RANK = {p: i for i, p in enumerate(POSITION_ORDER)}

FACE_STATS = ["pace", "shooting", "passing", "dribbling", "defending", "physic"]
GK_STATS = [
    "goalkeeping_diving", "goalkeeping_handling", "goalkeeping_kicking",
    "goalkeeping_positioning", "goalkeeping_reflexes", "goalkeeping_speed",
]

PLAYER_COLS = [
    "player_id", "player_url", "fifa_version", "fifa_update", "update_as_of",
    "short_name", "long_name", "player_positions", "overall", "age",
    "club_team_id", "club_name", "league_id", "league_name", "league_level",
    "club_position", "club_loaned_from", "nationality_name", "real_face",
    *FACE_STATS, *GK_STATS,
]

# Sample clubs for manual verification (team_id -> expected name)
SAMPLE_CLUBS = {243: "Real Madrid", 9: "Liverpool", 21: "FC Bayern München", 45: "Juventus", 73: "Paris Saint-Germain"}
SAMPLE_VERSIONS = [19, 24]


def md_table(df: pd.DataFrame, index: bool = False) -> str:
    """Render a DataFrame as a GitHub markdown table (no tabulate dependency)."""
    if index:
        df = df.reset_index()
    cols = [str(c) for c in df.columns]

    def cell(v) -> str:
        if isinstance(v, float) and pd.isna(v):
            return ""
        if v is None or v is pd.NA:
            return ""
        return str(v).replace("|", "\\|").replace("\n", " ")

    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for row in df.itertuples(index=False):
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines)


def pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def pos_sort_key(p: str) -> int:
    return POS_RANK.get(p, 99)


def formation_of(positions: list[str]) -> str:
    d = sum(p in DEFENDERS for p in positions)
    m = sum(p in MIDFIELDERS for p in positions)
    a = sum(p in ATTACKERS for p in positions)
    return f"{d}-{m}-{a}"


def example_values(path: Path) -> pd.DataFrame:
    """Column names, dtypes and the first non-null example value of each column."""
    head = pd.read_csv(path, nrows=5000, low_memory=False)
    rows = []
    for c in head.columns:
        non_null = head[c].dropna()
        ex = str(non_null.iloc[0]) if len(non_null) else "(all null in first 5000 rows)"
        if len(ex) > 70:
            ex = ex[:67] + "..."
        rows.append({"#": len(rows) + 1, "column": c, "dtype": str(head[c].dtype), "example": ex})
    return pd.DataFrame(rows)


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    out: list[str] = []
    w = out.append

    print("Reading CSVs...")
    players = pd.read_csv(PLAYERS_CSV, usecols=PLAYER_COLS, low_memory=False)
    teams = pd.read_csv(TEAMS_CSV, low_memory=False)
    players["fifa_version"] = players["fifa_version"].astype(int)
    teams["fifa_version"] = teams["fifa_version"].astype(int)
    players["club_team_id"] = players["club_team_id"].astype("Int64")
    versions = sorted(players["fifa_version"].unique())

    w("# Stage 01 — Data exploration report")
    w("")
    w("Generated by `pipeline/explore.py` from `data/raw/FIFA 15-24/male_players.csv` and `male_teams.csv`.")
    w("Version numbers below are `fifa_version` (15 = FIFA 15 … 24 = EA FC 24).")
    w("")

    # ---------------------------------------------------------------- a. Columns
    w("## a. Columns")
    w("")
    w(f"### male_players.csv ({len(players):,} rows)")
    w("")
    w(md_table(example_values(PLAYERS_CSV)))
    w("")
    w(f"### male_teams.csv ({len(teams):,} rows)")
    w("")
    w(md_table(example_values(TEAMS_CSV)))
    w("")

    # ---------------------------------------------------------------- b. Versions / updates
    w("## b. Versions, updates and row counts")
    w("")
    rows = []
    for v in versions:
        pv = players[players.fifa_version == v]
        tv = teams[teams.fifa_version == v]
        dup = pv.player_id.duplicated().sum()
        rows.append({
            "fifa_version": v,
            "fifa_update values": ", ".join(str(x) for x in sorted(pv.fifa_update.unique())),
            "update_as_of": ", ".join(sorted(pv.update_as_of.unique())),
            "player rows": len(pv),
            "duplicate player_id": dup,
            "team fifa_update": ", ".join(str(x) for x in sorted(tv.fifa_update.unique())),
            "team update_as_of": ", ".join(sorted(tv.update_as_of.unique())),
            "team rows": len(tv),
        })
    w(md_table(pd.DataFrame(rows)))
    w("")

    # Players missing from a single version (present in the version before and after)
    ids = {v: set(players[players.fifa_version == v].player_id) for v in versions}
    rows = []
    for v in versions[1:-1]:
        gap = (ids[v - 1] & ids[v + 1]) - ids[v]
        after = players[(players.fifa_version == v + 1) & players.player_id.isin(gap)].sort_values("overall", ascending=False)
        rows.append({
            "fifa_version": v,
            "absent (present in v-1 and v+1)": len(gap),
            "of which overall >= 80 in v+1": int((after.overall >= 80).sum()),
            "top examples (club / overall in v+1)": "; ".join(
                f"{r.short_name} ({r.club_name} / {r.overall})" for r in after.head(6).itertuples()
            ),
        })
    w("Players absent from a snapshot although present in the previous and next version "
      "(a gap here can hit a starting XI, see section d):")
    w("")
    w(md_table(pd.DataFrame(rows)))
    w("")

    # ---------------------------------------------------------------- c. Leagues and clubs
    w("## c. Top-5 leagues and clubs per league")
    w("")
    latest = max(versions)
    t_latest = teams[(teams.fifa_version == latest) & (teams.league_level == 1)]
    league_ids: dict[str, int] = {}
    for key, name, country in TARGET_LEAGUES:
        match = t_latest[(t_latest.league_name == name) & (t_latest.nationality_name == country)]
        ids = match.league_id.unique()
        if len(ids) != 1:
            raise SystemExit(f"Could not uniquely detect league {name} ({country}): {ids}")
        league_ids[key] = int(ids[0])
    id_to_key = {v: k for k, v in league_ids.items()}

    w(f"Leagues are detected by (league_name, team country) in version {latest}, then tracked by `league_id`.")
    w("")
    rows = []
    for key, name, country in TARGET_LEAGUES:
        lid = league_ids[key]
        t_names = teams[teams.league_id == lid].league_name.value_counts()
        p_names = players[players.league_id == lid].league_name.value_counts()
        rows.append({
            "league": key,
            "league_id": lid,
            "country": country,
            "league_name values seen with this id (teams file, rows)": "; ".join(f"{n} ({c})" for n, c in t_names.items()),
            "league_name values seen with this id (players file, rows)": "; ".join(f"{n} ({c})" for n, c in p_names.items()),
        })
    w(md_table(pd.DataFrame(rows)))
    w("")
    w("**Note:** `league_name` is *not* version-accurate. For older versions, clubs that have since been")
    w("relegated carry the name of their current league (e.g. FIFA 15 `league_id` 13 contains Hull City")
    w("labelled \"Championship\"). `league_id` (and `league_level`) are version-accurate, so the pipeline must")
    w("filter on `league_id`, never on `league_name`.")
    w("")

    top_teams = teams[teams.league_id.isin(league_ids.values())].copy()
    top_teams["league"] = top_teams.league_id.map(id_to_key)
    counts = top_teams.pivot_table(index="fifa_version", columns="league", values="team_id", aggfunc="count")
    counts = counts[[k for k, _, _ in TARGET_LEAGUES]]
    counts["total"] = counts.sum(axis=1)
    w("Clubs per league per version (from `male_teams.csv`, filtered on `league_id`):")
    w("")
    w(md_table(counts, index=True))
    w("")

    # Cross-check: clubs derived from the players file
    top_players = players[players.league_id.isin(league_ids.values())]
    p_clubs = top_players.groupby("fifa_version").club_team_id.nunique()
    mismatch_rows = []
    for v in versions:
        t_ids = set(top_teams[top_teams.fifa_version == v].team_id)
        p_ids = set(top_players[top_players.fifa_version == v].club_team_id.dropna().astype(int))
        mismatch_rows.append({
            "fifa_version": v,
            "clubs (teams file)": len(t_ids),
            "clubs (players file)": p_clubs.get(v, 0),
            "only in teams": len(t_ids - p_ids),
            "only in players": len(p_ids - t_ids),
        })
    w("Cross-check against distinct `club_team_id` of players whose `league_id` is a top-5 league:")
    w("")
    w(md_table(pd.DataFrame(mismatch_rows)))
    w("")

    # ---------------------------------------------------------------- d. XI counts
    w("## d. Starting XI completeness")
    w("")
    w("XI = players of the club (same `fifa_version`, `club_team_id`) whose `club_position` is not SUB, RES or null.")
    w("")
    squads = players.merge(
        top_teams[["fifa_version", "team_id", "team_name", "league"]],
        left_on=["fifa_version", "club_team_id"], right_on=["fifa_version", "team_id"], how="inner",
    )
    xi = squads[squads.club_position.notna() & ~squads.club_position.isin(NON_XI)].copy()
    xi_sizes = xi.groupby(["fifa_version", "team_id"]).size()
    gk_counts = xi[xi.club_position == "GK"].groupby(["fifa_version", "team_id"]).size()
    squad_sizes = squads.groupby(["fifa_version", "team_id"]).size()

    rows, bad = [], []
    for v in versions:
        tv = top_teams[top_teams.fifa_version == v]
        n11 = n_other = n_gk_bad = n_dup_pos = 0
        for _, t in tv.iterrows():
            size = int(xi_sizes.get((v, t.team_id), 0))
            gks = int(gk_counts.get((v, t.team_id), 0))
            positions = sorted(xi[(xi.fifa_version == v) & (xi.team_id == t.team_id)].club_position, key=pos_sort_key)
            dup_pos = len(positions) != len(set(positions))
            if size == 11:
                n11 += 1
            else:
                n_other += 1
            if gks != 1:
                n_gk_bad += 1
            if dup_pos:
                n_dup_pos += 1
            if size != 11 or gks != 1 or dup_pos:
                bad.append({
                    "fifa_version": v, "club": t.team_name, "league": t.league,
                    "squad size": int(squad_sizes.get((v, t.team_id), 0)), "XI count": size, "GKs": gks, "duplicate positions": "yes" if dup_pos else "",
                    "positions": " ".join(positions),
                })
        rows.append({
            "fifa_version": v, "clubs": len(tv), "exactly 11": n11, "not 11": n_other,
            "GK count != 1": n_gk_bad, "duplicate position codes": n_dup_pos,
        })
    w(md_table(pd.DataFrame(rows)))
    w("")
    if bad:
        w("Clubs failing any check (XI != 11, GK count != 1, or the same position code used twice):")
        w("")
        w(md_table(pd.DataFrame(bad)))
    else:
        w("**Every club in every version has exactly 11 starters, exactly one GK, and no repeated position code.**")
    w("")

    # ---------------------------------------------------------------- e. club_position values
    w("## e. Distinct `club_position` values")
    w("")
    vc_all = players.club_position.fillna("(null)").value_counts()
    vc_top = squads.club_position.fillna("(null)").value_counts()
    vc = pd.DataFrame({"all players": vc_all, "top-5 league squads": vc_top}).fillna(0).astype(int)
    vc = vc.sort_values("all players", ascending=False)
    vc.index.name = "club_position"
    w(md_table(vc, index=True))
    w("")
    null_pos = players[players.club_position.isna()]
    w(f"Rows with null `club_position`: {len(null_pos):,}; of these, {pct(null_pos.club_name.isna().mean())} "
      "also have a null `club_name` (players without a club).")
    w("")

    # ---------------------------------------------------------------- f. Formations
    w("## f. Derived formations")
    w("")
    w("Groups: D = " + ", ".join(sorted(DEFENDERS, key=pos_sort_key))
      + "; M = " + ", ".join(sorted(MIDFIELDERS, key=pos_sort_key))
      + "; A = " + ", ".join(sorted(ATTACKERS, key=pos_sort_key)) + ". GK excluded.")
    w("")
    club_xi = (
        xi.groupby(["fifa_version", "team_id"]).club_position
        .apply(lambda s: sorted(s, key=pos_sort_key)).reset_index()
    )
    club_xi["formation"] = club_xi.club_position.apply(formation_of)
    club_xi["signature"] = club_xi.club_position.apply(lambda ps: " ".join(p for p in ps if p != "GK"))
    fpiv = club_xi.pivot_table(index="formation", columns="fifa_version", values="team_id", aggfunc="count").fillna(0).astype(int)
    fpiv["total"] = fpiv.sum(axis=1)
    fpiv = fpiv.sort_values("total", ascending=False)
    w("D-M-A formation frequency per version:")
    w("")
    w(md_table(fpiv, index=True))
    w("")
    sig = club_xi.groupby("signature").agg(clubs=("team_id", "size"), formation=("formation", "first"))
    sig = sig.sort_values("clubs", ascending=False).reset_index()[["formation", "signature", "clubs"]]
    w(f"Exact outfield position sets (all versions, {len(sig)} distinct) — useful for the stage 3 mapping tests:")
    w("")
    w(md_table(sig))
    w("")

    # ---------------------------------------------------------------- g. Stats availability
    w("## g. Stats availability (null rates)")
    w("")
    players["is_gk"] = players.player_positions.fillna("").str.split(",").str[0].str.strip() == "GK"
    xi = xi.merge(players[["player_id", "fifa_version", "is_gk"]], on=["player_id", "fifa_version"], how="left")
    xi["xi_gk"] = xi.club_position == "GK"

    def null_table(df: pd.DataFrame, gk_col: str) -> tuple[pd.DataFrame, pd.DataFrame]:
        out_rows, gk_rows = [], []
        for v in versions:
            dv = df[df.fifa_version == v]
            of, gk = dv[~dv[gk_col]], dv[dv[gk_col]]
            r = {"fifa_version": v, "outfield n": len(of)}
            r.update({c: pct(of[c].isna().mean()) for c in FACE_STATS})
            r["goalkeeping_speed (outfield)"] = pct(of["goalkeeping_speed"].isna().mean())
            out_rows.append(r)
            g = {"fifa_version": v, "GK n": len(gk)}
            g.update({c.replace("goalkeeping_", "gk_"): pct(gk[c].isna().mean()) for c in GK_STATS})
            g["pace (GK)"] = pct(gk["pace"].isna().mean())
            gk_rows.append(g)
        return pd.DataFrame(out_rows), pd.DataFrame(gk_rows)

    of_all, gk_all = null_table(players, "is_gk")
    of_xi, gk_xi = null_table(xi, "xi_gk")
    w("### Top-5 league starting XI players (GK = `club_position` GK)")
    w("")
    w("Outfield face stats:")
    w("")
    w(md_table(of_xi))
    w("")
    w("Goalkeepers:")
    w("")
    w(md_table(gk_xi))
    w("")
    w("### All players (GK = first entry of `player_positions` is GK)")
    w("")
    w(md_table(of_all))
    w("")
    w(md_table(gk_all))
    w("")
    gk_speed_xi = xi[xi.xi_gk].groupby("fifa_version").goalkeeping_speed.agg(["min", "max", "mean"]).round(1)
    w("`goalkeeping_speed` range for XI goalkeepers per version (min / max / mean):")
    w("")
    w(md_table(gk_speed_xi, index=True))
    w("")
    outfield_gks = xi[xi.xi_gk & ~xi.is_gk.fillna(False)]
    gk_outfield = xi[~xi.xi_gk & xi.is_gk.fillna(False)]
    w(f"Consistency: XI players in the GK slot whose primary position is not GK: {len(outfield_gks)}; "
      f"XI players in an outfield slot whose primary position is GK: {len(gk_outfield)}.")
    w("")

    # ---------------------------------------------------------------- h. Image URLs
    w("## h. Player face and club logo URLs")
    w("")
    all_p_cols = pd.read_csv(PLAYERS_CSV, nrows=0).columns
    all_t_cols = teams.columns
    url_like_p = [c for c in all_p_cols if any(k in c for k in ("url", "face", "logo", "flag", "image"))]
    url_like_t = [c for c in all_t_cols if any(k in c for k in ("url", "face", "logo", "flag", "image"))]
    w(f"- `player_face_url` present in male_players.csv: **{'player_face_url' in all_p_cols}**")
    w(f"- `club_logo_url` present in male_teams.csv / male_players.csv: **{'club_logo_url' in all_t_cols or 'club_logo_url' in all_p_cols}**")
    w(f"- URL/image-like columns in male_players.csv: {', '.join(f'`{c}`' for c in url_like_p)}")
    w(f"- URL/image-like columns in male_teams.csv: {', '.join(f'`{c}`' for c in url_like_t)}")
    w("")
    w("Null rates of the columns that do exist:")
    w("")
    w(md_table(pd.DataFrame([
        {"column": "player_url", "null rate": pct(players.player_url.isna().mean())},
        {"column": "team_url", "null rate": pct(teams.team_url.isna().mean())},
        {"column": "real_face", "null rate": pct(players.real_face.isna().mean())},
    ])))
    w("")
    w("Examples (`player_url`, `team_url`):")
    w("")
    for u in players.player_url.dropna().head(3):
        w(f"- `{u}`")
    for u in teams.team_url.dropna().head(3):
        w(f"- `{u}`")
    w("")
    w("SoFIFA CDN URLs can be derived from ids (pattern used by earlier versions of this Kaggle dataset,")
    w("`players/<first 3 digits>/<last 3 digits>/<version>_120.png` with the id zero-padded to 6 digits):")
    w("")
    for _, r in xi[xi.fifa_version == latest].head(3).iterrows():
        pid = f"{int(r.player_id):06d}"
        w(f"- {r.short_name}: `https://cdn.sofifa.net/players/{pid[:3]}/{pid[3:]}/{latest}_120.png`")
    for tid in list(SAMPLE_CLUBS)[:3]:
        w(f"- {SAMPLE_CLUBS[tid]} logo: `https://cdn.sofifa.net/teams/{tid}/120.png`")
    w("")
    rf = xi.groupby("fifa_version").real_face.apply(lambda s: pct((s == "Yes").mean())).rename("real_face = Yes")
    w("Share of top-5 XI players with `real_face` = Yes (others get a generic in-game face):")
    w("")
    w(md_table(rf.to_frame(), index=True))
    w("")

    # ---------------------------------------------------------------- i. Loans
    w("## i. Loans")
    w("")
    w("Column `club_loaned_from` holds the parent club's name when the player is on loan; `club_name` / `club_team_id` "
      "is then the club the player is loaned *to* (the club the player actually plays for).")
    w("")
    rows = []
    for v in versions:
        pv = players[players.fifa_version == v]
        sv = squads[squads.fifa_version == v]
        xv = xi[xi.fifa_version == v]
        rows.append({
            "fifa_version": v,
            "loaned (all players)": int(pv.club_loaned_from.notna().sum()),
            "loaned in top-5 squads": int(sv.club_loaned_from.notna().sum()),
            "loaned in top-5 XIs": int(xv.club_loaned_from.notna().sum()),
            "club_name == club_loaned_from": int((pv.club_name == pv.club_loaned_from).sum()),
        })
    w(md_table(pd.DataFrame(rows)))
    w("")
    w("Since `player_id` is unique within each version (section b), a loaned player is listed exactly once — at the "
      "borrowing club — and is never in the parent club's squad or XI.")
    w("")
    ex = xi[(xi.fifa_version == latest) & xi.club_loaned_from.notna()].sort_values("overall", ascending=False).head(10)
    w(f"Examples: loaned players in top-5 XIs, version {latest}:")
    w("")
    w(md_table(ex[["short_name", "club_name", "club_position", "overall", "club_loaned_from"]]))
    w("")

    # ---------------------------------------------------------------- j. Samples
    w("## j. Sample XIs for manual verification")
    w("")
    for v in SAMPLE_VERSIONS:
        for tid, label in SAMPLE_CLUBS.items():
            sx = xi[(xi.fifa_version == v) & (xi.team_id == tid)].copy()
            name = sx.team_name.iloc[0] if len(sx) else label
            sx["rank"] = sx.club_position.map(pos_sort_key)
            sx = sx.sort_values("rank")
            w(f"### FIFA/FC {v} — {name} (team_id {tid}, formation {formation_of(list(sx.club_position))})")
            w("")
            w(md_table(sx[["short_name", "long_name", "club_position", "overall"]]))
            w("")

    # ---------------------------------------------------------------- k. Size estimate
    w("## k. Size estimate")
    w("")
    per_version = xi.groupby("fifa_version").size()
    w(f"Total starting-XI players across {len(versions)} versions: **{int(per_version.sum()):,}** "
      f"({int(per_version.min())}–{int(per_version.max())} per version).")
    w("")
    w("Estimate method: each XI player is serialised as a compact JSON object with ~15 fields "
      "(id, name, shortName, nation, age, positionInGame, positions[], overall, 6 stats, faceUrl, slot) plus a "
      "small per-team header; minified and gzip sizes are measured, not guessed.")
    w("")
    rows = []
    for v in versions:
        xv = xi[xi.fifa_version == v]
        teams_json = []
        for tid, g in xv.groupby("team_id"):
            plist = []
            for _, r in g.iterrows():
                pid = f"{int(r.player_id):06d}"
                if r.xi_gk:
                    stats = {k: (None if pd.isna(r[c]) else int(r[c])) for k, c in zip(
                        ["div", "han", "kic", "ref", "spd", "pos"],
                        ["goalkeeping_diving", "goalkeeping_handling", "goalkeeping_kicking",
                         "goalkeeping_reflexes", "goalkeeping_speed", "goalkeeping_positioning"])}
                else:
                    stats = {k: (None if pd.isna(r[c]) else int(r[c])) for k, c in zip(
                        ["pac", "sho", "pas", "dri", "def", "phy"], FACE_STATS)}
                plist.append({
                    "id": int(r.player_id), "name": r.long_name, "shortName": r.short_name,
                    "nation": r.nationality_name, "age": int(r.age), "positionInGame": r.club_position,
                    "positions": [p.strip() for p in str(r.player_positions).split(",")],
                    "overall": int(r.overall), "stats": stats,
                    "faceUrl": f"https://cdn.sofifa.net/players/{pid[:3]}/{pid[3:]}/{v}_120.png",
                    "slot": "XX",
                })
            teams_json.append({"id": int(tid), "name": g.team_name.iloc[0], "league": g.league.iloc[0],
                               "formation": "4-3-3", "xi": plist})
        blob = json.dumps({"version": int(v), "teams": teams_json}, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        rows.append({
            "fifa_version": v, "clubs": len(teams_json), "XI players": len(xv),
            "minified JSON (KB)": round(len(blob) / 1024, 1),
            "gzip (KB)": round(len(gzip.compress(blob)) / 1024, 1),
        })
    size_df = pd.DataFrame(rows)
    w(md_table(size_df))
    w("")
    w(f"All versions together: ~{size_df['minified JSON (KB)'].sum():.0f} KB minified, "
      f"~{size_df['gzip (KB)'].sum():.0f} KB gzipped.")
    w("")

    # ---------------------------------------------------------------- Appendix
    w("## Appendix — clubs per version and league")
    w("")
    w("Source: `male_teams.csv`, filtered on `league_id`. Names as they appear in the data.")
    w("")
    for v in versions:
        w(f"<details><summary>FIFA/FC {v}</summary>")
        w("")
        for key, _, _ in TARGET_LEAGUES:
            names = sorted(top_teams[(top_teams.fifa_version == v) & (top_teams.league == key)].team_name)
            w(f"- **{key}** ({len(names)}): " + ", ".join(names))
        w("")
        w("</details>")
        w("")

    # ---------------------------------------------------------------- Write report
    manual = f"{MANUAL_MARKER}\n\n## Findings & risks\n\n(To be written.)\n"
    if REPORT.exists():
        existing = REPORT.read_text(encoding="utf-8")
        if MANUAL_MARKER in existing:
            manual = existing[existing.index(MANUAL_MARKER):]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(out) + "\n" + manual, encoding="utf-8")
    print(f"Wrote {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
