"""Nation name (as in `nationality_name`) -> flag code for the app (D39).

Codes are lowercase ISO 3166-1 alpha-2, matching the file names of the `flag-icons` package, plus its
non-ISO extras: the UK home nations (gb-eng, gb-sct, gb-wls, gb-nir) and Kosovo (xk).
The table covers every nation that appears in any top-5 league squad in FIFA 15 - FC 24.
"""

import re

NATION_CODES: dict[str, str] = {
    "Afghanistan": "af",
    "Albania": "al",
    "Algeria": "dz",
    "Andorra": "ad",
    "Angola": "ao",
    "Antigua and Barbuda": "ag",
    "Argentina": "ar",
    "Armenia": "am",
    "Australia": "au",
    "Austria": "at",
    "Azerbaijan": "az",
    "Belarus": "by",
    "Belgium": "be",
    "Benin": "bj",
    "Bermuda": "bm",
    "Bolivia": "bo",
    "Bosnia and Herzegovina": "ba",
    "Brazil": "br",
    "Brunei Darussalam": "bn",
    "Bulgaria": "bg",
    "Burkina Faso": "bf",
    "Burundi": "bi",
    "Cameroon": "cm",
    "Canada": "ca",
    "Cape Verde Islands": "cv",
    "Central African Republic": "cf",
    "Chad": "td",
    "Chile": "cl",
    "China PR": "cn",
    "Colombia": "co",
    "Comoros": "km",
    "Congo": "cg",
    "Congo DR": "cd",
    "Costa Rica": "cr",
    "Croatia": "hr",
    "Cuba": "cu",
    "Curacao": "cw",
    "Cyprus": "cy",
    "Czech Republic": "cz",
    "Côte d'Ivoire": "ci",
    "Denmark": "dk",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "Egypt": "eg",
    "England": "gb-eng",
    "Equatorial Guinea": "gq",
    "Estonia": "ee",
    "Faroe Islands": "fo",
    "Finland": "fi",
    "France": "fr",
    "Gabon": "ga",
    "Gambia": "gm",
    "Georgia": "ge",
    "Germany": "de",
    "Ghana": "gh",
    "Greece": "gr",
    "Grenada": "gd",
    "Guinea": "gn",
    "Guinea Bissau": "gw",
    "Guyana": "gy",
    "Haiti": "ht",
    "Honduras": "hn",
    "Hungary": "hu",
    "Iceland": "is",
    "Iran": "ir",
    "Iraq": "iq",
    "Israel": "il",
    "Italy": "it",
    "Jamaica": "jm",
    "Japan": "jp",
    "Jordan": "jo",
    "Kazakhstan": "kz",
    "Kenya": "ke",
    "Korea DPR": "kp",
    "Korea Republic": "kr",
    "Kosovo": "xk",
    "Latvia": "lv",
    "Liberia": "lr",
    "Libya": "ly",
    "Liechtenstein": "li",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Macau": "mo",
    "Madagascar": "mg",
    "Mali": "ml",
    "Malta": "mt",
    "Mauritania": "mr",
    "Mexico": "mx",
    "Moldova": "md",
    "Montenegro": "me",
    "Montserrat": "ms",
    "Morocco": "ma",
    "Mozambique": "mz",
    "Netherlands": "nl",
    "New Caledonia": "nc",
    "New Zealand": "nz",
    "Niger": "ne",
    "Nigeria": "ng",
    "North Macedonia": "mk",
    "Northern Ireland": "gb-nir",
    "Norway": "no",
    "Palestine": "ps",
    "Panama": "pa",
    "Paraguay": "py",
    "Peru": "pe",
    "Philippines": "ph",
    "Poland": "pl",
    "Portugal": "pt",
    "Qatar": "qa",
    "Republic of Ireland": "ie",
    "Romania": "ro",
    "Russia": "ru",
    "Saint Kitts and Nevis": "kn",
    "Scotland": "gb-sct",
    "Senegal": "sn",
    "Serbia": "rs",
    "Sierra Leone": "sl",
    "Singapore": "sg",
    "Slovakia": "sk",
    "Slovenia": "si",
    "South Africa": "za",
    "South Sudan": "ss",
    "Spain": "es",
    "Suriname": "sr",
    "Sweden": "se",
    "Switzerland": "ch",
    "Tanzania": "tz",
    "Thailand": "th",
    "Togo": "tg",
    "Trinidad and Tobago": "tt",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Uganda": "ug",
    "Ukraine": "ua",
    "United States": "us",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
    "Venezuela": "ve",
    "Wales": "gb-wls",
    "Zambia": "zm",
    "Zimbabwe": "zw",
}

CODE_PATTERN = re.compile(r"^(?:[a-z]{2}|gb-(?:eng|sct|wls|nir))$")


class UnknownNationError(KeyError):
    """Raised when a nation has no flag code in NATION_CODES."""


def nation_code(nation: str) -> str:
    try:
        return NATION_CODES[nation]
    except KeyError:
        raise UnknownNationError(f"No flag code for nation {nation!r}; add it to pipeline/nations.py") from None
